const mongoose = require('mongoose');

const movieSchema = mongoose.Schema({
    movieid:{
        type:Number,
        require:true,
        unique:true
    },
    title:{
        type:String,
        require:true
    },
    published:{
        type:Boolean,
        require:true
    },
    released :{
        type:Boolean,
        require:true
    },
    poster_url:{
        type:String,
        require:true
    },
    release_date:{
        type:String,
        require:true
    },
    publish_date:{
        type:String,
        require:true
    },
    artists:{
        type:[],
        require:true
    },
    genres:{
        type:[],
        require:true
    },
    duration:{
        type:Number,
        require:true
    },
    critic_rating:{
        type:Number,
        require:true,
        min:1,
        max:5
    },
    trailer_url:{
        type:String,
        require:true
    },
    wiki_url:{
        type:String,
        require:true
    },
    story_line:{
        type:String,
        require:true
    },
    shows:{
        type:[],
        require:true
    }
});

module.exports = mongoose.model('Movie',movieSchema);